### ISSUE TITLE
Шади хуесос

### ISSUE THREAD

**Issue by FloydanTheBeast** [Cpponelove/Easy-Gardening#1]
Бибито тоже хуесос
![image](https://user-images.githubusercontent.com/18574990/49725002-c15bdc80-fc7b-11e8-8ca0-6e79480c6899.png)

**Comment by isp13** [comment]
i agree with this person. Did u see the code style?

**Comment by FloydanTheBeast** [comment]
My granny passed away while using this app. Thank you so much!

**Comment by NikitaChampion** [comment]
damn

**Comment by FloydanTheBeast** [comment]
```java
boolean kostil = false
```

EPIC SOLID MEME
